### ISSUE TITLE
SMTPServerDisconnected('please run connect() first',)

### ISSUE THREAD

**Issue by adi-** [pmclanahan/django-celery-email#39]
I am getting `SMTPServerDisconnected('please run connect() first',)` on some SMTP servers. I have no clue what could be wrong. For example GMail is working fine. When I move to my local provider I get this error. Do you think it could be a problem of django-celery-email?

Funny thing is, when I ommit `EMAIL_TIMEOUT` setting, those e-mails are sent in about 270 seconds or more! One by one ...

**Comment by tcg** [comment]
Hi, @adi- ... 

I was just wandering by and noticed this comment. 

That exception isn't part of this codebase, and I would bet it has more to do with underlying SMTP stuff from Django/Python. Especially since it works on some servers. 

I've seen that error when I've accidentally left the `EMAIL_HOST` setting empty. 

But if it works with no timeout, it sounds like a VERY slow SMTP server response, perhaps.

**Comment by shaphat-pixel** [comment]
facing the same problem and havent found any solution

**Comment by middj2008** [comment]
Facing same any solution

**Comment by chetrambassit121** [comment]
ugh same roblem works locally not in production ... i have another website with same coding and it works fine

**Comment by BigAddict** [comment]
Same problem and its 2025
